umg.on("@playerJoin", function(clientID)
    lp.forceSpawnSlot(lp.main.getContext():getPlot():getPPos(9,6), server.entities.dirt_slot, clientID)
    lp.forceSpawnItem(lp.main.getContext():getPlot():getPPos(10,6), server.entities.basic_seed, clientID)
    lp.forceSpawnItem(lp.main.getContext():getPlot():getPPos(10,7), server.entities.water_can, clientID)
end)